name: test
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.1

      - uses: actions/setup-node@v3
        with:
          node-version: '12'

      - id: get-version
        uses: battila7/get-version-action@v2

      - uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=test`date +%Y%m%d%H%M%S`"  >> $GITHUB_ENV

      - name: Login to Aliyun
        uses: docker/login-action@v3
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: transocksapp
          password: ${{ secrets.ALI_DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: egistry.cn-shanghai.aliyuncs.com/transocks/fobwifi:transip-rttys-${{ env.RELEASE_VERSION }}

